feat: check all weblate containers health
See https://github.com/WeblateOrg/docker/issues/2392

diff --git a/test-health b/test-health
--- a/test-health
+++ b/test-health
@@ -3,3 +3,33 @@ docker compose ps
 docker compose exec -T \
     --user weblate \
     weblate /app/bin/health_check
+
+failure=0
+
+container_id="$(docker compose ps -q weblate)"
+# shellcheck disable=SC2034
+for i in $(seq 30); do
+    container_status="$(docker inspect --format '{{json .State.Health.Status }}' "$container_id")"
+    if [ "$container_status" != '"starting"' ]; then
+        break
+    fi
+    echo "Waiting for container weblate to be up..."
+    sleep 1
+done
+
+# shellcheck disable=SC2013
+for service in $(sed -n 's/^  \(weblate.*\):$/\1/p' docker-compose.yml); do
+    container_id="$(docker compose ps -q "$service")"
+    container_status="$(docker inspect --format '{{json .State.Health.Status }}' "$container_id")"
+    echo "Container $service is $container_status"
+    if [ "$container_status" != '"healthy"' ]; then
+        failure=$((failure + 1))
+        docker inspect --format "{{json .State.Health }}" 67926a72d8b20e8ea379d7d03449fdde6d38bd39599b0b21b4fb880479049da3 | jq
+        echo
+    fi
+done
+
+if [ "$failure" -gt 0 ]; then
+    echo "Failed $failure services!"
+    exit 1
+fi
